// gen_symbols generates internal/parser/symbols_gen.go — the parser's seed symbol table.
// Run: go generate ./internal/parser/
package main

import (
	"fmt"
	"os"
	"regexp"
	"sort"
	"strings"

	"ish/internal/builtin"
	"ish/internal/core"
	"ish/internal/stdlib"
)

func main() {
	env := core.NewEnv(nil)
	stdlib.Register(env)

	type entry struct {
		name string
		kind string   // "SymBuiltin", "SymModule", "SymFn"
		fns  []string // only for SymModule
	}

	seen := map[string]*entry{}
	var names []string

	add := func(name, kind string) *entry {
		if e, ok := seen[name]; ok {
			return e
		}
		e := &entry{name: name, kind: kind}
		seen[name] = e
		names = append(names, name)
		return e
	}

	// Modules from stdlib.Register
	for _, modName := range []string{
		"Kernel", "List", "String", "Map", "Enum", "Tuple",
		"JSON", "CSV", "IO", "Math", "Regex", "Path", "Process",
	} {
		mod, ok := env.GetModule(modName)
		if !ok {
			continue
		}
		e := add(modName, "SymModule")
		for fn := range mod.Fns {
			e.fns = append(e.fns, fn)
		}
	}

	// Prelude .ish files add more functions to existing modules
	preludeDir := "internal/stdlib/prelude"
	entries, err := os.ReadDir(preludeDir)
	if err != nil {
		fmt.Fprintf(os.Stderr, "gen_symbols: cannot read %s: %v\n", preludeDir, err)
		os.Exit(1)
	}
	defRe := regexp.MustCompile(`^\s+def\s+(\w+)`)
	modRe := regexp.MustCompile(`^defmodule\s+(\w+)`)
	for _, de := range entries {
		if de.IsDir() || !strings.HasSuffix(de.Name(), ".ish") {
			continue
		}
		data, _ := os.ReadFile(preludeDir + "/" + de.Name())
		curMod := ""
		for _, line := range strings.Split(string(data), "\n") {
			if m := modRe.FindStringSubmatch(line); m != nil {
				curMod = m[1]
				continue
			}
			if curMod != "" {
				if m := defRe.FindStringSubmatch(line); m != nil {
					fn := m[1]
					if strings.HasPrefix(fn, "_") {
						continue
					}
					e := add(curMod, "SymModule")
					e.fns = append(e.fns, fn)
				}
			}
		}
	}

	// Deduplicate module function lists
	for _, e := range seen {
		if e.kind == "SymModule" {
			s := map[string]bool{}
			var deduped []string
			for _, fn := range e.fns {
				if !s[fn] {
					s[fn] = true
					deduped = append(deduped, fn)
				}
			}
			sort.Strings(deduped)
			e.fns = deduped
		}
	}

	// Kernel auto-imports: bare function names
	if km, ok := seen["Kernel"]; ok {
		for _, fn := range km.fns {
			add(fn, "SymFn")
		}
	}

	// Shell builtins
	for name := range builtin.Builtins {
		add(name, "SymBuiltin")
	}

	sort.Strings(names)

	// Generate
	var b strings.Builder
	b.WriteString("// Code generated by cmd/gen_symbols; DO NOT EDIT.\n\n")
	b.WriteString("package parser\n\n")
	b.WriteString("// SeedSymbols is the initial symbol table from stdlib, prelude, and builtins.\n")
	b.WriteString("var SeedSymbols = map[string]*Symbol{\n")
	for _, name := range names {
		e := seen[name]
		if e.kind == "SymModule" && len(e.fns) > 0 {
			b.WriteString(fmt.Sprintf("\t%q: {Kind: %s, Fns: map[string]bool{\n", name, e.kind))
			for _, fn := range e.fns {
				b.WriteString(fmt.Sprintf("\t\t%q: true,\n", fn))
			}
			b.WriteString("\t}},\n")
		} else {
			b.WriteString(fmt.Sprintf("\t%q: {Kind: %s},\n", name, e.kind))
		}
	}
	b.WriteString("}\n")

	outPath := "internal/parser/symbols_gen.go"
	if err := os.WriteFile(outPath, []byte(b.String()), 0644); err != nil {
		fmt.Fprintf(os.Stderr, "gen_symbols: %v\n", err)
		os.Exit(1)
	}
	fmt.Printf("gen_symbols: wrote %s\n", outPath)
}
